platform :ios, '11'
use_modular_headers!

target 'BinanceChainKitExample' do
  pod 'HsToolKit.swift', git: 'https://github.com/horizontalsystems/hs-tool-kit-ios'
  pod 'BinanceChainKit.swift', :path => '../'
end

target 'BinanceChainKitTests' do
  pod 'BinanceChainKit.swift', :path => '../'
end
